-- Complete seed for EU Savings Bank Map
-- Generated by scripts/import_csv.mjs on 2026-02-12
-- 78 banks total
-- Run this in Supabase SQL Editor after schema.sql and rls_policies.sql

-- 1. Erste Group (Sparkassen) — score 87
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Erste Group (Sparkassen)', 'Austria', 'AT', 'Vienna', 'Am Belvedere 1, 1100 Vienna', 48.2082, 16.3738, 'Erste Group / Sparkassen', 'https://www.erstegroup.com', 1819, 353000, 16700, 241000, 220000, 45500, 2000, 2024, 87, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparkasse.at/sgruppe/privatkunden/digitales-banking/apps/george-go-app'),
  ((SELECT id FROM b), 'open_banking', true, 'advanced', 'https://api.sparkasse.at'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.sparkasse.at/erstebank/privatkunden/konto-karten/onlinekonto'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.erstegroup.com/en/news-media/press-releases/2023/10/05/erste-bank-launches-austrias-first-financial-ai'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.erstegroup.com/en/news-media/press-releases/2021/07/01/erste-digital');

-- 2. Raiffeisen Bank International — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Raiffeisen Bank International', 'Austria', 'AT', 'Vienna', 'Am Stadtpark 9, 1030 Vienna', 48.2082, 16.3738, 'Raiffeisen', 'https://www.rbinternational.com', 1927, 215000, 18600, 120000, 99000, 44000, 1500, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.rbinternational.com/en/raipay.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://api.rbinternational.com/pages/getting-started/what-is-psd2-and-open-apis'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.at/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.rbinternational.com/en/raiffeisen/career.html');

-- 3. Raiffeisen-Landesbank Steiermark — score 40
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Raiffeisen-Landesbank Steiermark', 'Austria', 'AT', 'Graz', 'Radetzkystrasse 15, 8010 Graz', 47.0707, 15.4395, 'Raiffeisen Banking Group Austria', 'https://www.rlbstmk.at', 1927, 23000, 500, 17000, 15000, 1500, 70, 2024, 40, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.raiffeisen.at/stmk/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.raiffeisen.at/en/home.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.at/stmk/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.raiffeisen.at/stmk/rlb/de/meine-bank/karriere.html');

-- 4. Raiffeisenlandesbank NO-Wien — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Raiffeisenlandesbank NO-Wien', 'Austria', 'AT', 'Vienna', 'Friedrich-Wilhelm-Raiffeisen-Platz 1, 1020 Vienna', 48.2082, 16.3738, 'Raiffeisen Banking Group Austria', 'https://www.raiffeisenbank.at', 1898, 42000, 780, 30000, 26000, 2200, 90, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.raiffeisen.at/noew/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.raiffeisen.at/en/home.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.at/noew/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.raiffeisenbank.jobs/de/karriere-bei-raiffeisen/raiffeisen-als-arbeitgeber.html');

-- 5. Raiffeisenlandesbank Oberosterreich — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Raiffeisenlandesbank Oberosterreich', 'Austria', 'AT', 'Linz', 'Europaplatz 1a, 4020 Linz', 48.3069, 14.2858, 'Raiffeisen Banking Group Austria', 'https://www.rlbooe.at', 1900, 52000, 900, 38000, 33000, 3500, 130, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.raiffeisen.at/ooe/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.raiffeisen.at/en/home.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.at/ooe/de/privatkunden/konto.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.raiffeisen.at/ooe/rlb/de/karriere-bei-raiffeisen.html');

-- 6. Belfius Bank — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Belfius Bank', 'Belgium', 'BE', 'Brussels', 'Place Charles Rogier 11, 1210 Brussels', 50.8503, 4.3517, 'https://www.belfius.be', 1863, 230000, 4000, 160000, 140000, 16000, 600, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.belfius.be/about-us/en/who-we-are/what-we-do/mobile'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.belfius.be/devportal/en/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.belfius.be/retail/nl/becoming-a-customer/index.aspx'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.belfius.be/retail/nl/zelf-bankieren/campagnes/bbot/index.aspx'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://jobs.belfius.be/go/Talents-Tech/8939701/');

-- 7. KBC Brussels — score 87
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('KBC Brussels', 'Belgium', 'BE', 'Brussels', 'Avenue du Port 2, 1080 Brussels', 50.8503, 4.3517, 'KBC Group', 'https://www.kbcbrussels.be', 1935, 350000, 13000, 230000, 205000, 42000, 900, 2024, 87, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.kbcbrussels.be/retail/en/products/payments/self-banking/on-your-smartphone/mobile.html'),
  ((SELECT id FROM b), 'open_banking', true, 'advanced', 'https://developer.kbc.be/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.kbcbrussels.be/retail/en/products/payments/current-accounts/open-current-account.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.kbcbrussels.be/retail/en/campaign/save-time-by-asking-kate.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', 'https://newsroom.kbc.com/kbc-shifts-digital-transformation-and-customer-experience-up-a-gear-with-differently-the-next-level');

-- 8. Ceska sporitelna — score 73
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Ceska sporitelna', 'Czech Republic', 'CZ', 'Prague', 'Olbrachtova 1929/62, 140 00 Prague', 50.0755, 14.4378, 'Erste Group', 'https://www.csas.cz', 1825, 80000, 4500, 57000, 45000, 9500, 380, 2024, 73, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.csas.cz/cs/internetove-bankovnictvi/george'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developers.csas.cz/?lang=en'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.csas.cz/en/personal-finance/accounts-and-cards/basic-account'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.csas.cz/cs/internetove-bankovnictvi/george/hey-george'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.microsoft.com/en/customers/story/1442614428349876804-csas-banking-capital-markets-azure-en-czech');

-- 9. Nykredit — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Nykredit', 'Denmark', 'DK', 'Copenhagen', 'Kalvebod Brygge 1-3, 1780 Copenhagen V', 55.6761, 12.5683, 'Nykredit Group', 'https://www.nykredit.com', 1851, 215000, 1100, 145000, 130000, 4200, 70, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.nykredit.dk/dit-liv/daglig-okonomi/mitnykredit-netbank/mitnykredit-pa-mobil-og-tablet/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.nykredit.dk/personoplysninger-og-cookies/payment-service-directive-ii-psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.nykredit.dk/dit-liv/boligbank/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.nykredit.com/en-gb/career/nykredit-dci/');

-- 10. Spar Nord — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, founded_year, total_assets, customer_count, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Spar Nord', 'Denmark', 'DK', 'Aalborg', 57.0488, 9.9217, 1824, 20000, 400, 1500, 40, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', NULL);

-- 11. Aktia Bank — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Aktia Bank', 'Finland', 'FI', 'Helsinki', 'Mannerheimintie 14, 00100 Helsinki', 60.1699, 24.9384, 'https://www.aktia.com', 1991, 14000, 600, 9000, 8000, 900, 35, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.aktia.fi/fi/paivittaiset-raha-asiat/mobiilipankki'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.aktia.fi/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.aktia.fi/fi/asiakaspalvelu'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.aktia.com/en/careers');

-- 12. OP Financial Group — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('OP Financial Group', 'Finland', 'FI', 'Helsinki', 'Gebhardinaukio 1, 00510 Helsinki', 60.1699, 24.9384, 'OP Cooperative', 'https://www.op.fi', 1902, 192000, 4500, 130000, 98000, 14000, 370, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.op.fi/en/private-customers/digital-services/op-mobile'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.op.fi/en/corporate-customers/payment-transfers-and-cash-management/corporate-banking-api'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.op.fi/en/private-customers/become-op-customer-digitally'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.op.fi/en/about-op-pohjola/career/career-opportunities/development-and-technologies/');

-- 13. Savings Banks Group (Saastopankki) — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Savings Banks Group (Saastopankki)', 'Finland', 'FI', 'Helsinki', 'Teollisuuskatu 33, 00510 Helsinki', 60.1699, 24.9384, 'Savings Banks Group', 'https://www.saastopankki.fi', 1822, 16000, 1000, 11000, 9000, 1400, 120, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.saastopankki.fi/en'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.saastopankki.fi/en'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.saastopankki.fi/en'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', ''),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.saastopankki.fi/en');

-- 14. Credit Agricole Group — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Credit Agricole Group', 'France', 'FR', 'Paris', '12 Place des Etats-Unis, 92127 Montrouge', 48.8162, 2.3139, 'Credit Agricole', 'https://www.credit-agricole.com', 1894, 2763000, 54000, 1700000, 1200000, 154000, 7000, 2024, 67, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.credit-agricole.fr/particulier.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.ca-cib.com/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.credit-agricole.fr/particulier/compte.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', ''),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', 'https://www.credit-agricole.com/en/finance/financial-publications');

-- 15. Credit Mutuel Alliance Federale — score 73
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Credit Mutuel Alliance Federale', 'France', 'FR', 'Strasbourg', '4 Rue Frederic-Guillaume Raiffeisen, 67000 Strasbourg', 48.5734, 7.7521, 'Credit Mutuel', 'https://www.creditmutuel.fr', 1882, 1300000, 31000, 483000, 527000, 77000, 4000, 2024, 73, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.creditmutuel.fr/fr/particuliers/comptes/application-mobile-credit-mutuel.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.creditmutuel.fr/oauth2/en/devportal/open-banking-api.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.creditmutuel.fr/fr/particuliers/comptes/choisir-compte.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.creditmutuel.fr/cmne/fr/le-mag/assistant-virtuel.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', 'https://www.creditmutuelalliancefederale.fr/en/who-are-we/key-figures.html');

-- 16. Groupe BPCE (Caisse d'Epargne network) — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Groupe BPCE (Caisse d''Epargne network)', 'France', 'FR', 'Paris', '7 promenade Germaine Sablon, 75013 Paris', 48.8566, 2.3522, 'BPCE', 'https://www.groupebpce.com', 2009, 1584560, 35000, 723100, 851800, 100000, 7300, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.caisse-epargne.fr/banque-a-distance/applications-smartphone/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.groupebpce.com/en'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.caisse-epargne.fr/comptes-cartes/ouvrir-compte/'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.caisse-epargne.fr/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.groupebpce.com/en/all-the-latest-news/');

-- 17. Berliner Sparkasse — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Berliner Sparkasse', 'Germany', 'DE', 'Berlin', 'Alexanderplatz 2, 10178 Berlin', 52.52, 13.405, 'Sparkassen-Finanzgruppe', 'https://www.berliner-sparkasse.de', 1818, 46000, 1900, 32000, 27000, 4500, 85, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.berliner-sparkasse.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.berliner-sparkasse.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.berliner-sparkasse.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.berliner-sparkasse.de/de/home/toolbar/kontakt/whatsapp.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.berliner-sparkasse.de/de/home/ihre-sparkasse/dein-job.html');

-- 18. Berliner Volksbank — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Berliner Volksbank', 'Germany', 'DE', 'Berlin', 'Budapester Strasse 35, 10787 Berlin', 52.5076, 13.3439, 'BVR', 'https://www.berliner-volksbank.de', 1946, 18600, 1200, 14000, 12000, 2000, 70, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.berliner-volksbank.de/privatkunden/banking-apps/vr-banking-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.berliner-volksbank.de/rechtliche-hinweise/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.berliner-volksbank.de/privatkunden/girokonto-karten/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.berliner-volksbank.de/meine-bank/karriere.html');

-- 19. DZ Bank Group — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('DZ Bank Group', 'Germany', 'DE', 'Frankfurt', 'Platz der Republik, 60325 Frankfurt am Main', 50.1109, 8.6821, 'German Cooperative Financial Network', 'https://www.dzbank.com', 2001, 675000, 30000, 420000, 390000, 30000, 9000, 2024, 47, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://corporates.dzbank.com/content/firmenkunden/en/homepage/dzbanking.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://corporates.dzbank.com/content/firmenkunden/en/homepage/dzbanking/Third-party-interface.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', 'https://www.dzbank.com/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', 'https://www.dzbank.com/content/dzbank/en/home/we-are-dz-bank/careers/job-opportunities-worldwide.html');

-- 20. Frankfurter Sparkasse — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Frankfurter Sparkasse', 'Germany', 'DE', 'Frankfurt', 'Neue Mainzer Strasse 47-53, 60311 Frankfurt', 50.1109, 8.6821, 'Helaba / Sparkassen-Finanzgruppe', 'https://www.frankfurter-sparkasse.de', 1822, 21000, 900, 15000, 12000, 2200, 70, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.frankfurter-sparkasse.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.frankfurter-sparkasse.de/de/home/aktionen/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.frankfurter-sparkasse.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.frankfurter-sparkasse.de/de/home/service/kundenservicecenter.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.frankfurter-sparkasse.de/de/home/ihre-sparkasse/karriere.html');

-- 21. GLS Bank — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('GLS Bank', 'Germany', 'DE', 'Bochum', 'Christstrasse 9, 44789 Bochum', 51.4818, 7.2162, 'Cooperative GLS Gemeinschaftsbank', 'https://www.gls.de', 1974, 12000, 370, 9000, 7000, 950, 9, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.gls.de/privatkunden/gls-app/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.gls.de/psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.gls.de/privatkunden/konto/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.gls.de/karriere/');

-- 22. Hamburger Sparkasse (Haspa) — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Hamburger Sparkasse (Haspa)', 'Germany', 'DE', 'Hamburg', 'Adolphsplatz 3, 20457 Hamburg', 53.5511, 9.9937, 'Sparkassen-Finanzgruppe', 'https://www.haspa.de', 1827, 60000, 1500, 42000, 33000, 5000, 100, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.haspa.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.haspa.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.haspa.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.haspa.de/de/home/services-und-hilfe/die-top-links/live-chat.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.haspa.de/de/home/unternehmen-haspa/karriere/jobs.html');

-- 23. Kreissparkasse Koeln — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Kreissparkasse Koeln', 'Germany', 'DE', 'Cologne', 'Neumarkt 18-24, 50667 Cologne', 50.9375, 6.9603, 'Sparkassen-Finanzgruppe', 'https://www.ksk-koeln.de', 1853, 34000, 1600, 24000, 20000, 3800, 110, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.ksk-koeln.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.ksk-koeln.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.ksk-koeln.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.ksk-koeln.de/de/home/toolbar/kontakt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.ksk-koeln.de/de/home/ihre-sparkasse/karriere/stellenangebote.html');

-- 24. Nassauische Sparkasse — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Nassauische Sparkasse', 'Germany', 'DE', 'Wiesbaden', 50.0782, 8.2406, 'Sparkassen-Finanzgruppe', 'https://www.naspa.de', 1840, 15303, 700, 12456, 1626, 101, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'basic', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', NULL);

-- 25. Sparkasse Bremen — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparkasse Bremen', 'Germany', 'DE', 'Bremen', 'Am Brill 1-3, 28195 Bremen', 53.0793, 8.8017, 'Sparkassen-Finanzgruppe', 'https://www.sparkasse-bremen.de', 1825, 14000, 600, 10000, 8000, 1300, 40, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparkasse-bremen.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sparkasse-bremen.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparkasse-bremen.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparkasse-bremen.de/de/home/toolbar/kontakt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.sparkasse-bremen.de/de/home/ihre-sparkasse/karriere.html');

-- 26. Sparkasse Hannover — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparkasse Hannover', 'Germany', 'DE', 'Hannover', 'Raschplatz 4, 30161 Hannover', 52.3759, 9.732, 'Sparkassen-Finanzgruppe', 'https://www.sparkasse-hannover.de', 1823, 28000, 1200, 19000, 15000, 2700, 90, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparkasse-hannover.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sparkasse-hannover.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparkasse-hannover.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparkasse-hannover.de/de/home/toolbar/kontakt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.sparkasse-hannover.de/de/home/ihre-sparkasse/karriere.html');

-- 27. Sparkasse KoelnBonn — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparkasse KoelnBonn', 'Germany', 'DE', 'Cologne', 'Hahnenstrasse 57, 50667 Cologne', 50.9375, 6.9603, 'Sparkassen-Finanzgruppe', 'https://www.sparkasse-koelnbonn.de', 1826, 33000, 1000, 24000, 19000, 3600, 120, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparkasse-koelnbonn.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sparkasse-koelnbonn.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparkasse-koelnbonn.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparkasse-koelnbonn.de/de/home/toolbar/kontakt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.sparkasse-koelnbonn.de/de/home/ihre-sparkasse/karriere.html');

-- 28. Sparkassen-Finanzgruppe — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparkassen-Finanzgruppe', 'Germany', 'DE', 'Berlin', 'Charlottenstrasse 47, 10117 Berlin', 52.52, 13.405, 'Sparkassen-Finanzgruppe', 'https://www.sparkasse.de', 1778, 2500000, 50000, 1700000, 1600000, 300000, 12000, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparkasse.de/pk/produkte/konten-und-karten/finanzen-apps/app-sparkasse.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sparkasse.de/pk/ratgeber/finanzplanung/banking-tipps/psd-2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparkasse.de/pk/produkte/konten-und-karten/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparkasse.de/ueber-uns/kuenstliche-intelligenz/sparkassegpt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.dsv-gruppe.de/');

-- 29. Stadtsparkasse Duesseldorf — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Stadtsparkasse Duesseldorf', 'Germany', 'DE', 'Duesseldorf', 'Berliner Allee 33, 40212 Duesseldorf', 51.2277, 6.7735, 'Sparkassen-Finanzgruppe', 'https://www.sskduesseldorf.de', 1825, 18000, 700, 12000, 10000, 1800, 45, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sskduesseldorf.de/de/home/service/sparkassen-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sskduesseldorf.de/de/home/service/psd2.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sskduesseldorf.de/de/home/privatkunden/girokonto.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sskduesseldorf.de/de/home/toolbar/kontakt.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.sskduesseldorf.de/de/home/ihre-sparkasse/karriere.html');

-- 30. Stadtsparkasse München — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Stadtsparkasse München', 'Germany', 'DE', 'Munich', 48.1357, 11.579, 'Sparkassen-Finanzgruppe', 'https://www.sskm.de', 1824, 23699, 800, 18724, 2518, 90, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'basic', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', NULL);

-- 31. OTP Bank — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('OTP Bank', 'Hungary', 'HU', 'Budapest', 'Nador utca 16, 1051 Budapest', 47.4979, 19.0402, 'OTP Group', 'https://www.otpbank.hu', 1949, 106000, 17000, 74000, 56000, 38000, 1400, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.otpbank.hu/portal/en/ibmb-en'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.otpbank.hu/portal/en/psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.otpbank.hu/portal/en/retail/account/forint-account-packages'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.otpbank.hu/portal/en/about-us');

-- 32. Banca di Asti — score 27
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banca di Asti', 'Italy', 'IT', 'Asti', 'Piazza Liberta 23, 14100 Asti', 44.9008, 8.2064, 'https://www.bancadiasti.it', 1842, 17000, 500, 13000, 10000, 1700, 240, 2024, 27, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://bancadiasti.it/servizi-digitali-new/'),
  ((SELECT id FROM b), 'open_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', 'https://bancadiasti.it/conti-correnti-per-privati-e-famiglie/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://bancadiasti.it/lavora-con-noi');

-- 33. Banca Monte dei Paschi di Siena — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banca Monte dei Paschi di Siena', 'Italy', 'IT', 'Siena', 43.3188, 11.3308, 'https://www.mps.it', 1472, 121910, 5000, 82600, 87200, 16291, 1312, 2024, 60, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', NULL);

-- 34. Banca Popolare di Bari — score 27
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banca Popolare di Bari', 'Italy', 'IT', 'Bari', 'Corso Cavour 19, 70122 Bari', 41.1171, 16.8719, 'MCC Group', 'https://www.popolarebari.it', 1960, 18000, 1400, 13000, 11000, 2600, 220, 2024, 27, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.popolarebari.it/content/bpb/it/home/prodotti/appmobile.home_piccoleimprese_commercio_servizi.html'),
  ((SELECT id FROM b), 'open_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', 'https://www.popolarebari.it/content/bpb/it/home/prodotti/mi-.home.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.popolarebari.it/');

-- 35. Banca Popolare di Sondrio — score 40
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banca Popolare di Sondrio', 'Italy', 'IT', 'Sondrio', 'Piazza Garibaldi 16, 23100 Sondrio', 46.1699, 9.8713, 'https://www.popso.it', 1871, 56000, 3200, 42000, 35000, 3500, 350, 2024, 40, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.popso.it/servizi-digitali/app-scrigno-bps'),
  ((SELECT id FROM b), 'open_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.popso.it/prodotti/privati/servizi-digitali/servizi-digitali/appscrignobps'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.popso.it/home');

-- 36. BCC Iccrea Group — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('BCC Iccrea Group', 'Italy', 'IT', 'Rome', 'Via Lucrezia Romana 41-47, 00178 Rome', 41.9028, 12.4964, 'Iccrea Banca', 'https://www.gruppobcciccrea.it', 2019, 185000, 5200, 135000, 120000, 22500, 2500, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.gruppobcciccrea.it/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.gruppobcciccrea.it/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://generazionebcc.gruppobcciccrea.it/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.gruppobcciccrea.it/');

-- 37. Cassa Centrale Banca Group — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Cassa Centrale Banca Group', 'Italy', 'IT', 'Trento', 'Via Segantini 5, 38122 Trento', 46.0664, 11.1258, 'Cassa Centrale Banca', 'https://www.cassacentrale.it', 1974, 110000, 1600, 78000, 70000, 12000, 1500, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.cassacentrale.it/en/products/digital-banking-solutions/inbank'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.cassacentrale.it/en/products-and-services/products-banks/digital-banking-solutions'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.cassacentrale.it/en/products/digital-banking-solutions/inbank'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.cassacentrale.it/it/lavora-con-noi');

-- 38. CDP (Cassa Depositi e Prestiti) — score 7
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, founded_year, total_assets, employee_count, reporting_year, digital_score, status, featured)
  VALUES ('CDP (Cassa Depositi e Prestiti)', 'Italy', 'IT', 'Rome', 41.9028, 12.4964, 1850, 400000, 1100, 2024, 7, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'open_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'digital_onboarding', false, 'none', NULL),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', NULL);

-- 39. Banque et Caisse d'Epargne de l'Etat (Spuerkeess) — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banque et Caisse d''Epargne de l''Etat (Spuerkeess)', 'Luxembourg', 'LU', 'Luxembourg', '1 Place de Metz, L-1930 Luxembourg', 49.6116, 6.1319, 'https://www.spuerkeess.lu', 1856, 56000, 500, 43000, 33000, 1900, 55, 2024, 53, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.spuerkeess.lu/en/mobile/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.spuerkeess.lu/en/snet/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.spuerkeess.lu/en/private-customers/tools/application-to-set-up-a-business-relationship/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.spuerkeess.lu/en/about-us/');

-- 40. Banque Raiffeisen — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banque Raiffeisen', 'Luxembourg', 'LU', 'Leudelange', '4 Rue Leon Laval, L-3372 Leudelange', 49.5686, 6.0653, 'Raiffeisen Luxembourg', 'https://www.raiffeisen.lu', 1925, 13000, 250, 10000, 8000, 900, 40, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.raiffeisen.lu/en/private/daily-banking/mobile-payments/online-banking-r-net'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.raiffeisen.lu/en/psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.lu/en/private/daily-banking/new-client/open-banking-account'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.raiffeisen.lu/en/welcome-raiffeisen');

-- 41. Bank of Valletta — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Bank of Valletta', 'Malta', 'MT', 'Valletta', '58 Zachary Street, Valletta VLT 1130', 35.8989, 14.5146, 'https://www.bov.com', 1974, 15000, 400, 11000, 9000, 1500, 44, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.bov.com/mobile-banking-0'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.bov.com/Content/payment-services-directive'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://join.bov.com/'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.bov.com/content/get-in-touch-with-us'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.bov.com/careers');

-- 42. de Volksbank — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('de Volksbank', 'Netherlands', 'NL', 'Utrecht', 'Croeselaan 1, 3521 BJ Utrecht', 52.0907, 5.1214, 'https://www.devolksbank.nl', 2017, 74000, 3000, 55000, 45000, 3200, 650, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.asnbank.nl/online-en-mobiel-bankieren/mobiel-bankieren/aan-de-slag-met-de-asn-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://openbanking.devolksbank.nl/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.regiobank.nl/betalen/betaalrekening-openen.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://werkenbij.devolksbank.nl/nl/nl/search-results');

-- 43. Rabobank — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Rabobank', 'Netherlands', 'NL', 'Utrecht', 'Croeselaan 18, 3521 CB Utrecht', 52.0907, 5.1214, 'Cooperative Rabobank', 'https://www.rabobank.com', 1898, 749000, 10000, 470000, 430000, 49000, 430, 2024, 67, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.rabobank.nl/en/personal/online-banking/app'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developer.rabobank.nl'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.rabobank.nl/en/personal/payments/banking-account'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.rabobank.nl/particulieren/contact/chatbot'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://rabobank.jobs/en/expertise/it/');

-- 44. Triodos Bank — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Triodos Bank', 'Netherlands', 'NL', 'Driebergen-Rijsenburg', 'Hoofdstraat 10, 3972 LA Driebergen-Rijsenburg', 52.0517, 5.28, 'Triodos Group', 'https://www.triodos.com', 1980, 17000, 750, 13000, 10000, 1700, 40, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.triodos.nl/service/particulieren/bankieren/mobiel-bankieren'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.triodos.com/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.triodos.nl/veelgestelde-vragen/hoe-open-ik-als-nieuwe-klant-een-rekening-bij-triodos-bank?id=9f7a3f512b59'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.triodos.com/en/careers');

-- 45. Bank Norwegian (Nordax Group) — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Bank Norwegian (Nordax Group)', 'Norway', 'NO', 'Fornebu', 'Snaroyveien 36, 1364 Fornebu', 59.899, 10.627, 'Nordax Bank', 'https://www.banknorwegian.no', 2007, 42000, 1700, 30000, 27000, 650, 0, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.banknorwegian.no/'),
  ((SELECT id FROM b), 'open_banking', false, 'none', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.banknorwegian.no/kundeservice/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://careers.noba.bank/');

-- 46. SpareBank 1 Alliance — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('SpareBank 1 Alliance', 'Norway', 'NO', 'Oslo', 'Hammersborggata 11, 0179 Oslo', 59.9139, 10.7522, 'SpareBank 1 Alliance', 'https://www.sparebank1.no', 1996, 180000, 1200, 120000, 110000, 16000, 280, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparebank1.no/nb/bank/privat/daglig-bruk/mobilbank.html'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developer.sparebank1.no'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparebank1.no/nb/bank/privat/daglig-bruk/mobilbank.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparebank1.no/nb/sorost/privat/info/sammie-chatbot.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://sparebank1utvikling.medium.com');

-- 47. SpareBank 1 Nord-Norge — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('SpareBank 1 Nord-Norge', 'Norway', 'NO', 'Tromso', 'Storgata 65, 9008 Tromso', 69.6492, 18.9553, 'SpareBank 1 Alliance', 'https://www.sparebank1.no/nb/nord-norge', 1836, 62000, 650, 45000, 36000, 1100, 35, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparebank1.no/nb/nord-norge/privat/daglig-bruk/mobilbank.html'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developer.sparebank1.no'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparebank1.no/nb/nord-norge/privat/kundeservice/bestill/bli-kunde.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparebank1.no/nb/nord-norge/kundeservice/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://sparebank1utvikling.medium.com');

-- 48. SpareBank 1 Østlandet — score 80
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('SpareBank 1 Østlandet', 'Norway', 'NO', 'Hamar', 60.7945, 11.068, 'SpareBank 1 Alliance', 'https://www.sparebank1.no/ostlandet', 1845, 18003, 350, 1100, 37, 2024, 80, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', NULL);

-- 49. SpareBank 1 SMN — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('SpareBank 1 SMN', 'Norway', 'NO', 'Trondheim', 'Sondre gate 4, 7011 Trondheim', 63.4305, 10.3951, 'SpareBank 1 Alliance', 'https://www.sparebank1.no/nb/smn', 1823, 78000, 850, 56000, 47000, 1400, 46, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparebank1.no/nb/smn/privat/daglig-bruk/mobilbank.html'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developer.sparebank1.no'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparebank1.no/nb/smn/privat/kundeservice/bestill/bli-kunde.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparebank1.no/nb/smn/kundeservice/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://sparebank1utvikling.medium.com');

-- 50. SpareBank 1 SR-Bank — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('SpareBank 1 SR-Bank', 'Norway', 'NO', 'Stavanger', 'Christen Tranes gate 35, 4007 Stavanger', 58.969, 5.7331, 'SpareBank 1 Alliance', 'https://www.sr-bank.no', 1839, 85000, 1200, 60000, 50000, 1700, 50, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sparebank1.no/nb/sr-bank/privat/daglig-bruk/mobil-og-nettbank.html'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://developer.sparebank1.no'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sparebank1.no/nb/sr-bank/privat/kundeservice/bestill/bli-kunde.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.sparebank1.no/nb/sr-bank/privat/kundeservice.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://sparebank1utvikling.medium.com');

-- 51. Sparebanken Sor — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparebanken Sor', 'Norway', 'NO', 'Kristiansand', 'Radhusgata 14, 4611 Kristiansand', 58.1467, 7.9956, 'https://www.sor.no', 1824, 42000, 420, 30000, 24000, 900, 28, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.sor.no/kort-og-betaling/mobil-og-nettbank/mobilbank/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.sor.no/felles/info/open-banking/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.sor.no/privat/bli-kunde'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.sor.no/felles/om-sparebanken-sor/ledige-stillinger/');

-- 52. Sparebanken Vest — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Sparebanken Vest', 'Norway', 'NO', 'Bergen', 'Jonsvollsgaten 2, 5011 Bergen', 60.3913, 5.3221, 'https://www.spv.no', 1823, 51000, 500, 36000, 30000, 1050, 31, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.spv.no/dagligbank/nett-og-mobilbank/mobilbank'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.spv.no/kundeservice/psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.spv.no/bli-kunde'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.spv.no/om-oss/jobb');

-- 53. Bank Pocztowy — score 33
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, founded_year, total_assets, customer_count, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Bank Pocztowy', 'Poland', 'PL', 'Bydgoszcz', 53.1235, 18.0084, 1990, 4000, 1500, 1800, 470, 2024, 33, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'basic', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', NULL),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', NULL);

-- 54. PKO Bank Polski — score 93
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('PKO Bank Polski', 'Poland', 'PL', 'Warsaw', 52.2237, 21.0186, 'https://www.pkobp.pl', 1919, 122807, 12100, 141287, 68772, 25600, 1193, 2024, 93, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'advanced', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', NULL);

-- 55. Banco BPI — score 87
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banco BPI', 'Portugal', 'PT', 'Porto', 41.1628, -8.6389, 'CaixaBank Group', 'https://www.bancobpi.pt', 1981, 41072, 1800, 39300, 30300, 4352, 299, 2024, 87, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', NULL),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', NULL),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', NULL);

-- 56. Banco Montepio — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banco Montepio', 'Portugal', 'PT', 'Lisbon', 'Rua Aurea 219-241, 1100-062 Lisbon', 38.7223, -9.1393, 'Associacao Mutualista Montepio', 'https://www.bancomontepio.pt', 1844, 30000, 1600, 22000, 18000, 3800, 300, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.bancomontepio.pt/en/individuals/everyday-banking/digital-banking'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.bancomontepio.pt/en/open-banking-apis'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.bancomontepio.pt/en/individuals/everyday-banking/open-account-online'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.bancomontepio.pt/en');

-- 57. Caixa Geral de Depositos — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Caixa Geral de Depositos', 'Portugal', 'PT', 'Lisbon', 'Av. Joao XXI 63, 1000-300 Lisbon', 38.7223, -9.1393, 'https://www.cgd.pt', 1876, 120000, 3300, 89000, 54000, 6200, 520, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.cgd.pt/Particulares/Contas/Caixadirecta/Pages/Caixadirecta.aspx'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.cgd.pt/English/Institutional/News/Pages/Open-Banking-SIBS-API-Market.aspx'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.cgd.pt/Particulares/Contas/Abertura-conta/Pages/Abertura-conta.aspx'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.cgd.pt/Particulares/Contas/Caixadirecta/Pages/Caixadirecta.aspx'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.cgd.pt/English/Institutional/Pages/Institutional_v2.aspx');

-- 58. Banca Transilvania — score 67
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Banca Transilvania', 'Romania', 'RO', 'Cluj-Napoca', 'Calea Dorobantilor 30-36, 400117 Cluj-Napoca', 46.7712, 23.6236, 'BT Group', 'https://www.bancatransilvania.ro', 1993, 38000, 4300, 28000, 22000, 10000, 500, 2024, 67, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.bancatransilvania.ro/en/personal-banking/online-banking/mobile-banking'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://en.bancatransilvania.ro/open-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.bancatransilvania.ro/en/personal-banking/current-accounts'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.bancatransilvania.ro/en/contact'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.bancatransilvania.ro/en/about-us/careers');

-- 59. CEC Bank — score 33
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('CEC Bank', 'Romania', 'RO', 'Bucharest', 'Calea Victoriei 13, Bucharest', 44.4268, 26.1025, 'Romanian State', 'https://www.cec.ro', 1864, 17000, 2900, 12000, 9000, 6400, 1000, 2024, 33, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'intermediate', 'https://www.cec.ro/persoane-fizice/mobile-banking'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.cec.ro/open-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', 'https://www.cec.ro/persoane-fizice/conturi-si-pachete'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.cec.ro/despre-cec-bank/cariere');

-- 60. Slovenska sporitelna — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Slovenska sporitelna', 'Slovakia', 'SK', 'Bratislava', 'Tomasikova 48, 832 37 Bratislava', 48.1486, 17.1077, 'Erste Group', 'https://www.slsp.sk', 1825, 25000, 2200, 18000, 16000, 3700, 190, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.slsp.sk/sk/george'),
  ((SELECT id FROM b), 'open_banking', true, 'intermediate', 'https://www.slsp.sk/en/business/online-banking/psd2-api-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'basic', 'https://www.slsp.sk/sk/ludia/uvery/uver-na-byvanie/digitalna-hypoteka'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.slsp.sk/sk/ludia/bezpecnost/co-robit-v-pripade-problemov'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.erstegroup.com/en/news-media/press-releases/2021/07/01/erste-digital');

-- 61. Nova Ljubljanska Banka (NLB) — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Nova Ljubljanska Banka (NLB)', 'Slovenia', 'SI', 'Ljubljana', 'Trg republike 2, 1000 Ljubljana', 46.0569, 14.5058, 'https://www.nlb.si', 1889, 25000, 1900, 17000, 13000, 6000, 230, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.nlb.si/en/osebno/digitalne-storitve/nlb-klik'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.nlb.me/apidocumentation/apiproducts'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.nlb.si/en/osebno/accounts-and-packages'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.nlb.si/en/osebno/contact'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.nlbgroup.com/int-en/careers');

-- 62. ABANCA — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('ABANCA', 'Spain', 'ES', 'A Coruna', 'Cantón Claudino Pita 2, 15300 Betanzos', 43.3623, -8.4115, 'ABANCA Corporacion Bancaria', 'https://www.abanca.com', 2011, 128000, 2200, 92000, 78000, 6800, 650, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.abanca.com/es/banca-a-distancia/banca-movil/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.abanca.com/es/banca-a-distancia/psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://cuentas.abanca.com/'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.abanca.com/es/ayuda/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://empleo.abanca.com/');

-- 63. CaixaBank — score 93
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('CaixaBank', 'Spain', 'ES', 'Valencia', 'Calle Pintor Sorolla 2-4, 46002 Valencia', 39.4699, -0.3763, 'https://www.caixabank.es', 1904, 630000, 20300, 462000, 366000, 46200, 4300, 2024, 93, 'published', true)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.caixabank.es/particular/banca-digital/appcaixabanknow_en.html'),
  ((SELECT id FROM b), 'open_banking', true, 'advanced', 'https://apistore.caixabank.com/home_en.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'advanced', 'https://www.caixabank.es/particular/holabank/become-customer.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'intermediate', 'https://www.caixabank.com/es/actualidad/noticias/caixabank-crea-un-asistente-virtual-basado-en-inteligencia-artificial-para-dar-apoyo-a-todos-los-empleados-de-su-red'),
  ((SELECT id FROM b), 'devops_cloud', true, 'advanced', 'https://www.caixabanktech.com/en/about-us/');

-- 64. Caja Rural de Navarra — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Caja Rural de Navarra', 'Spain', 'ES', 'Pamplona', 'Plaza de los Fueros 1, 31005 Pamplona', 42.8125, -1.6458, 'Grupo Caja Rural', 'https://www.cajaruraldenavarra.com', 1904, 18000, 500, 13000, 11000, 1100, 140, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.cajaruraldenavarra.com/en/node/4431'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.cajarural.com/es/psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.cajaruraldenavarra.com/es/particulares/cuentas'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.cajaruraldenavarra.com/es/conocenos/empleo/');

-- 65. Cajamar Caja Rural — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Cajamar Caja Rural', 'Spain', 'ES', 'Almeria', 'Plaza de Barcelona 5, 04006 Almeria', 36.834, -2.4637, 'Grupo Cooperativo Cajamar', 'https://www.cajamar.es', 1966, 64000, 3900, 47000, 39000, 5600, 900, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.cajamar.es/en/particulares/productos-y-servicios/banca-a-distancia/banca-movil/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.cajamar.es/en/comun/psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.cajamar.es/en/particulares/productos-y-servicios/cuentas/pack-wefferent/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.cajamar.es/es/comun/informacion-corporativa/empleo/');

-- 66. Ibercaja Banco — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Ibercaja Banco', 'Spain', 'ES', 'Zaragoza', 'Plaza Basilio Paraiso 2, 50008 Zaragoza', 41.6488, -0.8891, 'Ibercaja Group', 'https://www.ibercaja.es', 2011, 105000, 3600, 76000, 58000, 5400, 900, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.ibercaja.es/particulares/banca-digital/servicios/app-ibercaja/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.ibercaja.es/particulares/corner-del-especialista/informacion-psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.ibercaja.es/particulares/cuentas-tarjetas/cuentas/cuenta-vamos/'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.ibercaja.es/particulares/atencion-cliente/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://empleo.ibercaja.es/');

-- 67. Kutxabank — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Kutxabank', 'Spain', 'ES', 'Bilbao', 'Gran Via 30-32, 48009 Bilbao', 43.263, -2.935, 'Kutxabank Group', 'https://www.kutxabank.es', 2012, 86000, 2500, 62000, 50000, 5800, 850, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://portal.kutxabank.es/cs/Satellite/kb/es/particulares/productos/banca-omnicanal/banca-movil/pys'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://portal.kutxabank.es/cs/Satellite/kb/es/particulares/sobre-kutxabank/psd2/generico'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://portal.kutxabank.es/cs/Satellite/kb/es/particulares/hazte-cliente/pys'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://portal.kutxabank.es/cs/Satellite/kb/es/particulares/servicio-atencion-al-cliente-/generico'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://portal.kutxabank.es/cs/Satellite/kb/es/particulares/otras-zonas-geograficas-0/areas-de-trabajo/generico');

-- 68. Laboral Kutxa — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Laboral Kutxa', 'Spain', 'ES', 'Mondragon', 'Paseo Jose Maria Arizmendiarrieta, 20500 Mondragon', 43.0644, -2.4914, 'https://www.laboralkutxa.com', 1959, 28000, 1200, 21000, 17000, 2400, 280, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.laboralkutxa.com/es/personas/servicios/banca-online/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://blog.laboralkutxa.com/es/cambios-identificacion-online-banco-normativa-pagos-psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.laboralkutxa.com/es/personas/cuentas-y-tarjetas/cuentas/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.laboralkutxa.com/es/personas/trabaja-con-nosotros/');

-- 69. Unicaja Banco — score 53
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Unicaja Banco', 'Spain', 'ES', 'Malaga', 'Avenida de Andalucia 10-12, 29007 Malaga', 36.7213, -4.4214, 'Fundacion Unicaja', 'https://www.unicajabanco.es', 1884, 98000, 4700, 70000, 55000, 7600, 960, 2024, 53, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.unicajabanco.es/en/banca-digital'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.unicajabanco.es/es/faqs/banca-digital/psd2'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.unicajabanco.es/en/cuenta-online'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.unicajabanco.es/en/ayuda-y-contacto'),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://joven.unicajabanco.es/');

-- 70. Lansforsakringar Bank — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Lansforsakringar Bank', 'Sweden', 'SE', 'Stockholm', 'Tegeluddsvagen 11-13, 115 41 Stockholm', 59.3293, 18.0686, 'Lansforsakringar AB', 'https://www.lansforsakringar.se', 1997, 90000, 4000, 65000, 52000, 2200, 130, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.lansforsakringar.se/stockholm/privat/bank/appen/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.lansforsakringar.se/stockholm/om-oss/psd2/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.lansforsakringar.se/stockholm/privat/bank/bli-bankkund/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.lansforsakringar.se/stockholm/om-oss/jobba-hos-oss/');

-- 71. Swedbank and Savings Banks — score 73
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Swedbank and Savings Banks', 'Sweden', 'SE', 'Sundbyberg', 'Landsvagen 40, 172 63 Sundbyberg', 59.3613, 17.971, 'Sparbankerna + Swedbank', 'https://www.swedbank.com', 1820, 312000, 7400, 186000, 172000, 16000, 240, 2024, 73, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.swedbank.se/en/private/our-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'advanced', 'https://www.swedbank.com/openbanking.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.swedbank.se/privat/bli-kund.html'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.swedbank.se/en/contact-us.html'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.swedbank.com/openbanking.html');

-- 72. Raiffeisen Switzerland — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, parent_group, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Raiffeisen Switzerland', 'Switzerland', 'CH', 'St. Gallen', 'Raiffeisenplatz 4, 9001 St. Gallen', 47.4245, 9.3767, 'Raiffeisen Group', 'https://www.raiffeisen.ch', 1899, 297860, 2000, 240000, 220000, 12000, 780, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.raiffeisen.ch/rch/de/privatkunden/e-banking/mobile-banking-zahlungen-scannen.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.raiffeisen.ch/rch/de/firmenkunden/liquiditaet-und-zahlungsverkehr/electronic-banking/kmu-eservices/open-banking.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.raiffeisen.ch/rch/de/privatkunden/konten-und-bezahlen.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.raiffeisen.ch/rch/de/ueber-uns/karriere.html');

-- 73. Coventry Building Society — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Coventry Building Society', 'United Kingdom', 'GB', 'Coventry', 'Economic House, High Street, Coventry', 52.4068, -1.5197, 'https://www.coventrybuildingsociety.co.uk', 1884, 71370, 2000, 50000, 43000, 3000, 70, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.coventrybuildingsociety.co.uk/member/support/banking-app.html'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.coventrybuildingsociety.co.uk/legal/open-banking.html'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.coventrybuildingsociety.co.uk/member/product/current-account.html'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.coventrybuildingsociety.co.uk/careers.html');

-- 74. Leeds Building Society — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Leeds Building Society', 'United Kingdom', 'GB', 'Leeds', '105 Albion Street, Leeds LS1 5AS', 53.8008, -1.5491, 'https://www.leedsbuildingsociety.co.uk', 1875, 30000, 1000, 24000, 18000, 1800, 50, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.leedsbuildingsociety.co.uk/member-support/mobile-app/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.leedsbuildingsociety.co.uk/legal/open-banking/'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.leedsbuildingsociety.co.uk/savings/online-saver/'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.leedsbuildingsociety.co.uk/careers/');

-- 75. Nationwide Building Society — score 60
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Nationwide Building Society', 'United Kingdom', 'GB', 'Swindon', 'Nationwide House, Pipers Way, Swindon', 51.5558, -1.7797, 'https://www.nationwide.co.uk', 1884, 318240, 16300, 247000, 210000, 18000, 600, 2024, 60, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.nationwide.co.uk/help/online-banking/mobile-banking-app/'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://developer.nationwideopenbanking.co.uk'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.nationwide.co.uk/current-accounts/flexaccount/'),
  ((SELECT id FROM b), 'ai_chatbot', true, 'basic', 'https://www.nationwide.co.uk/help/contact-us/chat/'),
  ((SELECT id FROM b), 'devops_cloud', true, 'intermediate', 'https://www.nationwide-jobs.co.uk/technology');

-- 76. Principality Building Society — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Principality Building Society', 'United Kingdom', 'GB', 'Cardiff', 'Principality Buildings, Queen Street, Cardiff', 51.4816, -3.1791, 'https://www.principality.co.uk', 1860, 16380, 500, 12000, 10000, 1100, 53, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.principality.co.uk/ways-to-bank/mobile-app'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.principality.co.uk/help-and-guidance/legal/open-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.principality.co.uk/savings/current-account'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.principality.co.uk/careers');

-- 77. Skipton Building Society — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Skipton Building Society', 'United Kingdom', 'GB', 'Skipton', 'The Bailey, Skipton, BD23 1DN', 53.9614, -2.0166, 'https://www.skipton.co.uk', 1853, 42120, 1200, 30000, 26000, 2800, 80, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.skipton.co.uk/help-and-support/app'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.skipton.co.uk/open-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.skipton.co.uk/mortgages/first-time-buyers/track-record-mortgage'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.skipton.co.uk/about-us/careers');

-- 78. Yorkshire Building Society — score 47
WITH b AS (
  INSERT INTO banks (name, country, country_code, city, address, latitude, longitude, website, founded_year, total_assets, customer_count, deposit_volume, loan_volume, employee_count, branch_count, reporting_year, digital_score, status, featured)
  VALUES ('Yorkshire Building Society', 'United Kingdom', 'GB', 'Bradford', 'Yorkshire House, Yorkshire Drive, Bradford', 53.795, -1.7594, 'https://www.ybs.co.uk', 1864, 77220, 3000, 56000, 47000, 3700, 220, 2024, 47, 'published', false)
  RETURNING id
)
INSERT INTO digital_features (bank_id, category, present, maturity_level, evidence_url) VALUES
  ((SELECT id FROM b), 'mobile_banking', true, 'advanced', 'https://www.ybs.co.uk/ways-to-bank/mobile-app'),
  ((SELECT id FROM b), 'open_banking', true, 'basic', 'https://www.ybs.co.uk/legal/open-banking'),
  ((SELECT id FROM b), 'digital_onboarding', true, 'intermediate', 'https://www.ybs.co.uk/current-accounts'),
  ((SELECT id FROM b), 'ai_chatbot', false, 'none', NULL),
  ((SELECT id FROM b), 'devops_cloud', true, 'basic', 'https://www.ybs.co.uk/careers');
